version: "3.8"

services:
  db:
    image: postgres:15
    container_name: zafira_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: zafira
      POSTGRES_PASSWORD: zafira_pass
      POSTGRES_DB: zafira_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../back_end
      dockerfile: Dockerfile
    container_name: zafira_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://zafira:zafira_pass@db:5432/zafira_db
    ports:
      - "3001:3001"
    volumes:
      - ../back_end:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ../front_end
      dockerfile: Dockerfile
    container_name: zafira_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ../front_end:/app
      - /app/node_modules
    command: npm run dev

  adminer:
    image: adminer
    container_name: zafira_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db-data:
