version: "3.8"

services:
  db:
    image: postgres:15
    container_name: zafira_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: zafira_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3001:3001"
      - "5555:5555" #prisma studio
    volumes:
      - ../backend:/app
      - /app/node_modules
    command:
    - sh
    - -c
    - "npx prisma migrate deploy && npx prisma db seed && npm run start:dev"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: zafira_frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev

  adminer:
    image: adminer
    container_name: zafira_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db-data:
